M48
; DRILL file {KiCad (5.99.0-9801-g46d71f0d23)} date 03/17/21 00:26:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-03-17T00:26:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-9801-g46d71f0d23)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T1C0.0433
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T2C0.0630
; #@! TA.AperFunction,ComponentDrill,NonPlated,NPTH
T3C0.1024
%
G90
G05
T1
; not plated pad hole
X7.7736Y-3.4757
T2
X8.7579Y-3.4757
T3
X7.7894Y-5.3674
X8.7421Y-5.3674
T0
M30
